wandb_version: 1

batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: COPIOUS
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704863601.637104
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.35.2
      8:
      - 1
      - 5
      13: linux-x86_64
